[colors.primary]
background = '#151218'
foreground = '#e8e0e8'

[colors.selection]
text = '#e8e0e8'
background = '#553b71'

[colors.cursor]
text = '#151218'
cursor = '#dabaf9'

[colors.normal]
black   = '#151218'
red     = '#ff728b'
green   = '#7cf999'
yellow  = '#ffdb72'
blue    = '#c9a4ec'
magenta = '#583d73'
cyan    = '#dabaf9'
white   = '#f7efff'

[colors.bright]
black   = '#9b95a1'
red     = '#ff9fb0'
green   = '#a5ffba'
yellow  = '#ffe8a5'
blue    = '#e4c8ff'
magenta = '#e8d1ff'
cyan    = '#f0e1ff'
white   = '#fbf8ff'
